 platform :ios, '12.0'

target '8-Ball' do
  use_frameworks!
pod 'SwiftLint', '~> 0.45'
pod 'SwiftGen', '~> 6.1'
pod 'SnapKit'
pod 'RealmSwift', '~>10'
pod 'RAMAnimatedTabBarController'
pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'

end
